# Setup
title:               'CS 184: Computer Graphics'
tagline:             'Honey, I Upped the Viscosity!'
# baseurl:             ''
# paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate

# Build settings
markdown: kramdown

# Custom vars
version:             1.0
google_analytics_id: #UA-XXXX-Y